/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.12, using .NET Server 4.0.0 template (version 0)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2024 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://roswel.cz/Example/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 11.11.2024
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace roswel.roswel
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class DataTypes
    {
    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the ExampleStructure Object.
        /// </summary>
        public const uint ExampleStructure = 5003;

        /// <summary>
        /// The identifier for the http://roswel.cz/Example/ Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example_ = 5004;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectTypes
    {
    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the Boolean Object.
        /// </summary>
        public const uint ExampleStructure_Boolean = 6001;

        /// <summary>
        /// The identifier for the String Object.
        /// </summary>
        public const uint ExampleStructure_String = 6002;

        /// <summary>
        /// The identifier for the DefaultAccessRestrictions Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__DefaultAccessRestrictions = 6012;

        /// <summary>
        /// The identifier for the DefaultRolePermissions Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__DefaultRolePermissions = 6010;

        /// <summary>
        /// The identifier for the DefaultUserRolePermissions Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__DefaultUserRolePermissions = 6011;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__IsNamespaceSubset = 6003;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__NamespacePublicationDate = 6004;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__NamespaceUri = 6005;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__NamespaceVersion = 6006;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__StaticNodeIdTypes = 6007;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__StaticNumericNodeIdRange = 6008;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___roswel_cz_Example__StaticStringNodeIdPattern = 6009;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the ExampleStructure Object.
        /// </summary>
        public static readonly ExpandedNodeId ExampleStructure = new ExpandedNodeId(Objects.ExampleStructure, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example_ = new ExpandedNodeId(Objects.Namespaces_http___roswel_cz_Example_, Namespaces.roswel);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectTypeIds
    {
    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the ExampleStructure_Boolean Variable.
        /// </summary>
        public static readonly ExpandedNodeId ExampleStructure_Boolean = new ExpandedNodeId(Variables.ExampleStructure_Boolean, Namespaces.roswel);

        /// <summary>
        /// The identifier for the ExampleStructure_String Variable.
        /// </summary>
        public static readonly ExpandedNodeId ExampleStructure_String = new ExpandedNodeId(Variables.ExampleStructure_String, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__DefaultAccessRestrictions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__DefaultAccessRestrictions = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__DefaultAccessRestrictions, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__DefaultRolePermissions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__DefaultRolePermissions = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__DefaultRolePermissions, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__DefaultUserRolePermissions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__DefaultUserRolePermissions = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__DefaultUserRolePermissions, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__IsNamespaceSubset, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__NamespacePublicationDate, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__NamespaceUri, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__NamespaceVersion, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__StaticNodeIdTypes, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__StaticNumericNodeIdRange, Namespaces.roswel);

        /// <summary>
        /// The identifier for the Namespaces_http___roswel_cz_Example__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___roswel_cz_Example__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___roswel_cz_Example__StaticStringNodeIdPattern, Namespaces.roswel);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the Boolean component.
        /// </summary>
        public const string Boolean = "Boolean";
        /// <summary>
        /// The BrowseName for the ExampleStructure component.
        /// </summary>
        public const string ExampleStructure = "ExampleStructure";
        /// <summary>
        /// The BrowseName for the String component.
        /// </summary>
        public const string String = "String";
        /// <summary>
        /// The BrowseName for the http://roswel.cz/Example/ component.
        /// </summary>
        public const string http___roswel_cz_Example_ = "http://roswel.cz/Example/";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the roswel namespace.
        /// </summary>
        public const string roswel = "http://roswel.cz/Example/";

        /// <summary>
        /// The URI for the roswelXsd namespace.
        /// </summary>
        public const string roswelXsd = "http://roswel.cz/Example/Types.xsd";
    }
    #endregion
}

